### ISSUE TITLE
what happened? atom.xml feed available?

### ISSUE THREAD

**Issue by jrochkind** [rubysec/rubysec.github.io#16]
What happened to rubysec.com? This repo no longer represents `https://rubysec.com/`?

I had been following the previous atom feed at https://rubysec.com/atom.xml, and aggregating it on http://rubyland.news.  Is there a replacement atom or rss feed?

**Comment by mveytsman** [comment]
@jrochkind 
We rewrote the webpage to allow users to submit vulnerabilities directly, so it's no longer a static page (that needed to be updated manually). We're going to push it to this repo and bring back the advisory feed shortly.

I'll let you know as soon as it's up,  Sorry for the delay!

**Comment by jrochkind** [comment]
> We're going to push it to this repo and bring back the advisory feed shortly.
> I'll let you know as soon as it's up, Sorry for the delay!

Hooray! I'm glad you're bringing back the feed, thanks for the update.

**Comment by jrochkind** [comment]
Please note here in this issue when the feed is back, so anyone can watch this issue to be notified? Thanks!

**Comment by mveytsman** [comment]
yup, I'll close it and ping you when it's back :)

**Comment by jrochkind** [comment]
I'm wondering what the entries in the feed will _link_ to, since the new website also doesn't seem to include a page/url for each vulnerability listed.  I actually rather liked the old website, and found it quite useful!  

But I'm sure you'll come up with something useful and look forward to finding out -- thanks very much for this service, it is very important.  

Personally I think a good atom/rss feed increases it's value quite a bit and makes a whole lot of sense for ruby security warnings, is a very useful community service, so I'm glad you're planning on bringing it back.

**Comment by phillmv** [comment]
@jrochkind hello! please see: https://github.com/rubysec/rubysec.com and https://rubysec.com/ and https://rubysec.com/atom.xml
