### ISSUE TITLE
Add action to generate rss feed

### ISSUE THREAD

**Issue by phillmv** [rubysec/rubysec.github.io#17]
Per https://github.com/rubysec/rubysec.com/issues/14, it'd be cool and useful if we could offer folks an rss feed so they could consume the data in other ways.

I recently became adept with generating static gh-pages from actions, so should anyone want to write a script that generates an atom/rss feed given the contents of the ruby-advisory-db, I'd be happy to string that into a GitHub action.

**Comment by reedloden** [comment]
We have the RSS feed now (technically, it's Atom, but whatever), but we still need GitHub Actions to run on any commits made to ruby-advisory-db that will then run `rake advisories` in this repository.

**Comment by reedloden** [comment]
ok, I automated this. :-)

**Comment by jrochkind** [comment]
Thank you!
